### ISSUE TITLE
Error table database - Using MySQL

### ISSUE THREAD

**Issue by viniropke99** [beave/meer#14]
Segue o erro de tabela abaixo: Teria como concertar?

HTTP (CAMPO COM TAMANHO PEQUENO)

[E] [05/05/2020 15:13:54] - [output-plugins/mysql.c, line 111] MySQL/MariaDB Error [1406:] "Data too long for column 'http_method' at row 1" Offending SQL statement: INSERT INTO http (sid,cid,hostname,url,xff,http_content_type,http_method,http_user_agent,http_refer,protocol,status,length) VALUES (1,20782,'','mstshash=Administr','','','\\x03\\0\\0/*\\xE0\\0\\0\\0\\0\\0C       ookie:','','','',0,200)

TLS - ERRO NA DATA

[E] [05/04/2020 03:29:07] - [output-plugins/mysql.c, line 111] MySQL/MariaDB Error [1292:] "Incorrect datetime value: '0000-00-00 00:00:00' for column 'notbefore' at row 1" Offending SQL statement: INSERT INTO tls (sid,cid,subject,issuerdn,serial,fingerprint,session_resumed,sni,version,notbefore,notafter) VALUES (1,11254,'','',0,'','','','SSLv2','0000-00-00 00:00:00','0000-00-00 00:00:00')

**Comment by beave** [comment]
Hello.    The 'http_method' looks like it needs to be increased.   I'll see if I can address these ASAP

**Comment by viniropke99** [comment]
There are problems in the table TLS, SMTP and others. Control the data problem.

I can send you the mistakes I have here, to solve it. Would there be another means of contact?

**Comment by beave** [comment]
You can send them here or via a pull request if you want.   Whatever works best for you.

**Comment by viniropke99** [comment]
**I wonder if this error is due to connection problem with the server?**

`[output-plugins/mysql.c, line 62] MySQL Error 2003: "Can't connect to MySQL server on '172.16.142.95' (101)"`

**Below is the meer LOG file, after 3 days of running it gave a problem. Something related to errors in MySQL correct? Attached is the log.**

[log.txt](https://github.com/beave/meer/files/4647372/log.txt)

**Comment by viniropke99** [comment]
### **Attached to the above code due to bad formatting**
[log.txt](https://github.com/beave/meer/files/4647369/log.txt)

**Comment by beave** [comment]
Hello...   The error "Consider increasing 'payload-buffer-size' in Suricata" is actually a Suricata issue, not Meer.  In your Suricata configuration is an option "payload-buffer-size".  If this size is to small,  the payload gets truncated and the JSON appears incomplete to Meer.   Try increasing that value "131072" (128k) and restarting Suricata.  I'll bet this resolves your issue. 

The connection issue is a MySQL issue.   

Let me know how it works out!

**Comment by viniropke99** [comment]
Okay, I'll do what you said, if it works I close the topic.

**Comment by viniropke99** [comment]
**Would it be this?**

 ```
types:
         - alert:
              payload: yes             # enable dumping payload in Base64
              payload-buffer-size: 128kb # max size of payload buffer to output in eve-log
             # payload-printable: yes   # enable dumping payload in printable (lossy) format
             # packet: yes              # enable dumping of packet (without stream segments)
             # metadata: no             # enable inclusion of app layer metadata with alert. Default yes
             # http-body: yes           # Requires metadata; enable dumping of http body in Base64
             # http-body-printable: yes # Requires metadata; enable dumping of http body in printable format
             # Enable the logging of tagged packets for rules using the
             # "tag" keyword.
             tagged-packets: yes

```
